### ISSUE TITLE
Annotation name

### ISSUE THREAD

**Issue by u-mulder** [cycle/annotated#10]
Shouldn't annotation `though` be changed to `through` (i.e. "using", "by means of")?

**Comment by wolfy-j** [comment]
It has already been changed like that. But we are keeping backward compatible attribute (which originated after typo). It will be removed in upcoming MAJOR releases.

**Comment by wolfy-j** [comment]
Yes, we will add this change in an upcoming release (we already addressed typo in schema-builder). Though, we will have to build proper fallback first for legacy declarations.

**Comment by TianNex** [comment]
yes,i think so
