### ISSUE TITLE
doctrine/inflector version

### ISSUE THREAD

**Issue by the-toster** [cycle/annotated#11]
Hi, thank you for this library.

It looks like this package silently depends on `doctrine/inflector ^1.4` API, here for example - https://github.com/cycle/annotated/blob/7dd29c0864e08a95f75d268ac0c9f5b65c3266eb/src/Configurator.php#L40

This dependency satisfied by `cycle/orm`, which is requires doctrine/inflector ^1.3, and usually install 1.4

But, It may cause problems (like in my case), when application already has 1.3 version of `inflector`.

Maybe `doctrine/inflector ^1.4` dependency should be added to this package?

**Comment by wolfy-j** [comment]
Hi,

you are correct, however, the dependency defined in cycle/orm package: https://github.com/cycle/orm/blob/master/composer.json#L10

The main problem is that Doctrine/Inflector 1.3 and 1.4 are not compatible. We will enforce the 1.4 version in cycle/orm, thank you for the catch.
