### ISSUE TITLE
Enhance documentation pls

### ISSUE THREAD

**Issue by rumatakira** [cycle/annotated#12]
Do u know that 
`/** @HasOne(target=Profile::class, load="eager") */ `

don't work without 
`use Cycle\Annotated\Annotation\Relation\HasOne`

and so on will all entities from \Relation

and this is not obviously - people need to study your code.

**Comment by wolfy-j** [comment]
Hi, 

it is the default behavior of Doctrine Annotations and it's the first thing written in documentation about annotations:
https://github.com/cycle/docs/blob/master/annotated/prerequisites.md#prerequisites

> Cycle is using the Doctrine/Annotations package, make sure that annotations are loadable (use) and the syntax is correct.
