### ISSUE TITLE
PHP 8 Attributes

### ISSUE THREAD

**Issue by shyim** [cycle/annotated#14]
It would be cool if we could use PHP 8 Attributes for defining the schema

**Comment by wolfy-j** [comment]
In progress - https://github.com/spiral/attributes

**Comment by SerafimArts** [comment]
P.S. Current state and roadmap: https://github.com/spiral/framework/issues/351

**Comment by roxblnfk** [comment]
Done in https://github.com/cycle/annotated/pull/17
