### ISSUE TITLE
Possible ManyToMany typo?

### ISSUE THREAD

**Issue by igbanam** [cycle/annotated#23]
I'm reading through the docs and I see

```
    /** @ManyToMany(target = "Tag", though = "UserTag") */
    protected $tags;
```

At first glance, I read this as "entity has many `Tag` _through_ `UserTag`" where `UserTag` is the join class somewhat. Thought to fix that and realized 👇🏾  this is how it's defined. 

https://github.com/cycle/annotated/blob/master/src/Annotation/Relation/ManyToMany.php#L59

Could this be a case of a typo carried over because of IDE smarts? If this isn't the case, what's the thought process? I see [this commit](https://github.com/cycle/annotated/commit/eef0b9ee35c509e4a7cde7cc7658e5f90a503bd3) introduces `"though"`, but the commit message doesn't really say why.

I know this is 2 years old, so it's a long shot; but I had to ask

**Comment by roxblnfk** [comment]
This typo will be fixed in the next major update https://github.com/cycle/annotated/blob/2.0/src/Annotation/Relation/ManyToMany.php#L87

**Comment by igbanam** [comment]
Awesome. Thanks.
